# Generated by Django 4.1.7 on 2023-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanceCategoryModel",
            fields=[
                ("uid", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("uid", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.TextField()),
                ("pwd", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                ("video_id", models.UUIDField(primary_key=True, serialize=False)),
                ("file_path", models.TextField()),
                ("embeds", models.TextField()),
                ("fps", models.IntegerField()),
                (
                    "dance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="App.dancecategorymodel",
                    ),
                ),
                (
                    "uploader_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="App.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                ("uid", models.UUIDField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "videoId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.videomodel"
                    ),
                ),
                (
                    "writerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.usermodel"
                    ),
                ),
            ],
        ),
    ]
