# Generated by Django 4.1.7 on 2023-04-17 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("videoId", models.UUIDField(default=uuid.uuid4)),
                ("writerId", models.UUIDField(default=uuid.uuid4)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DanceCategoryModel",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.TextField()),
                ("pwd", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoAngleModel",
            fields=[
                ("embeds", models.TextField()),
                ("video_id", models.UUIDField(primary_key=True, serialize=False)),
                ("fps", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                ("video_id", models.UUIDField(primary_key=True, serialize=False)),
                ("uploader_id", models.UUIDField()),
                ("title", models.TextField()),
                ("dance", models.UUIDField()),
                ("content", models.TextField(default="")),
            ],
        ),
    ]
