# Generated by Django 4.2 on 2023-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodel",
            name="category",
            field=models.UUIDField(default="5398d5cb-4dbd-4353-a3fe-99daf4fae5c4"),
            preserve_default=False,
        ),
    ]
