# Generated by Django 4.2 on 2023-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodel",
            name="dance",
            field=models.UUIDField(null=True),
        ),
    ]
