# Generated by Django 4.1.7 on 2023-04-17 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='videoId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='writerId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
