# Generated by Django 4.1.3 on 2022-12-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_userdance_rename_video_id_videomodel_video_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("image", models.ImageField(upload_to="%Y/%m/%d")),
            ],
        ),
        migrations.AlterField(
            model_name="userdance",
            name="image_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userdance",
            name="video_id",
            field=models.UUIDField(),
        ),
    ]
