# Generated by Django 4.2 on 2023-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_videoanglemodel_remove_videomodel_embeds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodel",
            name="dance",
            field=models.UUIDField(),
        ),
    ]
