# Generated by Django 4.2 on 2023-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_videomodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodel",
            name="category",
            field=models.UUIDField(null=True),
        ),
    ]
