# Generated by Django 4.2 on 2023-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_videomodel_dance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoanglemodel",
            name="angle_id",
        ),
        migrations.AlterField(
            model_name="videoanglemodel",
            name="video_id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
