# Generated by Django 4.2 on 2023-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_remove_videoanglemodel_angle_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videomodel",
            name="fps",
        ),
        migrations.AddField(
            model_name="videoanglemodel",
            name="fps",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
