# Generated by Django 4.1.3 on 2022-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Video_id', models.UUIDField(primary_key=True, serialize=False)),
                ('uploader_id', models.TextField()),
                ('post_id', models.TextField()),
                ('angles', models.JSONField()),
                ('path', models.FileField(upload_to='')),
                ('video_lenghth', models.IntegerField()),
                ('fps', models.IntegerField()),
            ],
        ),
    ]
